mysql:
  username: root
  password: 123456
  schema: catalog_admin
  url: localhost:3306


server:
  port: 8080
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # One IO thread per CPU core us a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2