version: '3.7'

services:
  mysql:
    container_name: catalog_admin_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=catalog_admin
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - catalog_admin_network

networks:
  catalog_admin_network: